<template>
	<div class="grid-container">
		<div class="search-form">
			<el-form :inline="true" :model="formInline">
			  	<el-form-item label="时间">
			    	<el-date-picker
				      	v-model="formInline.dateTime"
				      	type="daterange"
				      	placeholder="选择日期范围">
				    </el-date-picker>
			  	</el-form-item>
			  	<el-form-item label="损益标识">
				    <el-select v-model="formInline.profit" placeholder="损益标识">
				      <el-option label="区域一" value="shanghai"></el-option>
				      <el-option label="区域二" value="beijing"></el-option>
				    </el-select>
			  	</el-form-item>
			</el-form>
		</div>
		<div class="grid-toolbar">
			<button class="tool-btn btn-export">导出表格</button>
		</div>

		<div class="grid-content">
			<div class="statistic-content">
				<p>
					统计：
					<span>供应商N</span>
					<span>产品分类数M</span>
					<span>批号/型号/货号数量N</span>
					<span>sku数量M</span>
					<span>商品数量N</span>
				</p>
			</div>
			<el-table
			    :data="tableData"
			    v-loading.body="loading"
			    stripe
			    style="width: 100%">
			    <el-table-column
			      	prop="createDate"
			      	label="时间"
			      	width="150">
			    </el-table-column>
			    <el-table-column
			      	prop="stockArea"
			      	label="库区"
			      	width="150">
			    </el-table-column>
			    <el-table-column
			      	prop="stockType"
			      	label="库区类型"
			      	width="150">
			    </el-table-column>
			    <el-table-column
			      	prop="stockLocation"
			      	label="库位"
			      	width="150">
			    </el-table-column>
			    <el-table-column
			      	prop="goodsBarCode"
			      	label="商品条码"
			      	width="150">
			    </el-table-column>
			    <el-table-column
			      	prop="consignor"
			      	label="货主"
			      	width="250">
			    </el-table-column>
			    <el-table-column
			      	prop="supplier"
			      	label="供应商"
			      	width="250">
			    </el-table-column>
			    <el-table-column
			      	prop="classify"
			      	label="产品分类"
			      	width="150">
			    </el-table-column>
			    <el-table-column
			      	prop="brand"
			      	label="品牌"
			      	width="150">
			    </el-table-column>
			    <el-table-column
			      	prop="batchNo"
			      	label="批号/型号/货号"
			      	width="150">
			    </el-table-column>
			    <el-table-column
			      	prop="productName"
			      	label="产品名称"
			      	width="150">
			    </el-table-column>规格
			    <el-table-column
			      	prop="specification"
			      	label="规格"
			      	width="150">
			    </el-table-column>
			    <el-table-column
			      	prop="unit"
			      	label="单位"
			      	width="100">
			    </el-table-column>
			    <el-table-column
			      	prop="stockNum"
			      	label="库存量"
			      	width="100">
			    </el-table-column>
			    <el-table-column
			      	prop="inventoryResults"
			      	label="盘点结果"
			      	width="150">
			    </el-table-column>
			    <el-table-column
			      	prop="count"
			      	label="数量"
			      	width="100">
			    </el-table-column>
			</el-table>
		</div>
		<div class="grid-page">
			<el-pagination
	          	@size-change="handleSizeChange"
	          	@current-change="handleCurrentChange"
	          	:current-page.sync="currentPage"
	          	:page-sizes="[10, 20, 50, 100]"
	          	:page-size="pageSize"
	          	layout="total,->, prev, pager, next, jumper, sizes"
	          	:total="tableData.length">
	        </el-pagination>
		</div>
	</div>
</template>

<script type="text/javascript">
	export default {
	    name: 'detailed',
	    data:function(){
	    	return {
	    		formInline: {
	    			dateTime:'',
	    			profit:''
		        },
		        loading:true,
		        tableData: [],
		        currentPage: 1,
		        pageSize:10
	    	}
	    },
	    mounted:function(){
	    	this.loadData();
	    },
	    methods: {
	    	loadData:function(){
	  			this.loading = true;
	  			this.tableData=[{
	  				goodsId:'1',
	  				stockArea:'仓储1区',
	  				stockType:'仓储区',
	  				stockLocation:'A12-2-4-008',
		        	goodsBarCode:'SP2017984',
		        	consignor:'杭州塑料制品厂',
		        	supplier:'杭州化工集团有限公司',
		        	classify:'手机',
		        	brand:'华为',
		        	batchNo:'白色',
		        	productName:'荣耀',
		        	specification:'40*70',
		        	unit:'部',
		        	stockNum:'60',
		        	inventoryResults:'损',
		        	count:'100',
		        	handoverNum:'80',
		        	createDate:'2016-05-02'
		        },{
	  				goodsId:'2',
		        	stockArea:'仓储1区',
		        	stockType:'仓储区',
		        	stockLocation:'A12-2-4-008',
		        	type:'采购入库',
		        	goodsBarCode:'SP2017985',
		        	consignor:'杭州塑料制品厂',
		        	supplier:'杭州化工集团有限公司',
		        	classify:'手机',
		        	brand:'华为',
		        	batchNo:'白色',
		        	productName:'荣耀',
		        	specification:'40*70',
		        	unit:'部',
		        	stockNum:'60',
		        	inventoryResults:'损',
		        	count:'100',
		        	handoverNum:'80',
		        	createDate:'2016-05-02'
		        },{
	  				goodsId:'3',
		        	stockArea:'仓储1区',
		        	stockType:'仓储区',
		        	stockLocation:'A12-2-4-008',
		        	type:'采购入库',
		        	goodsBarCode:'SP2017986',
		        	consignor:'杭州塑料制品厂',
		        	supplier:'杭州化工集团有限公司',
		        	classify:'手机',
		        	brand:'华为',
		        	batchNo:'白色',
		        	productName:'荣耀',
		        	specification:'40*70',
		        	unit:'部',
		        	stockNum:'60',
		        	inventoryResults:'损',
		        	count:'100',
		        	handoverNum:'80',
		        	createDate:'2016-05-02'
		        },{
	  				goodsId:'3',
		        	stockArea:'仓储1区',
		        	stockType:'仓储区',
		        	stockLocation:'A12-2-4-008',
		        	type:'采购入库',
		        	goodsBarCode:'SP2017987',
		        	consignor:'杭州塑料制品厂',
		        	supplier:'杭州化工集团有限公司',
		        	classify:'手机',
		        	brand:'华为',
		        	batchNo:'白色',
		        	productName:'荣耀',
		        	specification:'40*70',
		        	unit:'部',
		        	stockNum:'60',
		        	inventoryResults:'损',
		        	count:'100',
		        	handoverNum:'80',
		        	createDate:'2016-05-02'
		        },{
	  				goodsId:'4',
		        	stockArea:'仓储1区',
		        	stockType:'仓储区',
		        	stockLocation:'A12-2-4-008',
		        	type:'采购入库',
		        	goodsBarCode:'SP2017988',
		        	consignor:'杭州塑料制品厂',
		        	supplier:'杭州化工集团有限公司',
		        	classify:'手机',
		        	brand:'华为',
		        	batchNo:'白色',
		        	productName:'荣耀',
		        	specification:'40*70',
		        	unit:'部',
		        	stockNum:'60',
		        	inventoryResults:'损',
		        	count:'100',
		        	handoverNum:'80',
		        	createDate:'2016-05-02'
		        },{
	  				goodsId:'5',
		        	stockArea:'仓储1区',
		        	stockType:'仓储区',
		        	stockLocation:'A12-2-4-008',
		        	type:'采购入库',
		        	goodsBarCode:'SP2017989',
		        	consignor:'杭州塑料制品厂',
		        	supplier:'杭州化工集团有限公司',
		        	classify:'手机',
		        	brand:'华为',
		        	batchNo:'白色',
		        	productName:'荣耀',
		        	specification:'40*70',
		        	unit:'部',
		        	stockNum:'60',
		        	inventoryResults:'损',
		        	count:'100',
		        	handoverNum:'80',
		        	createDate:'2016-05-02'
		        },{
	  				goodsId:'6',
		        	stockArea:'仓储1区',
		        	stockType:'仓储区',
		        	stockLocation:'A12-2-4-008',
		        	type:'采购入库',
		        	goodsBarCode:'SP2017910',
		        	consignor:'杭州塑料制品厂',
		        	supplier:'杭州化工集团有限公司',
		        	classify:'手机',
		        	brand:'华为',
		        	batchNo:'白色',
		        	productName:'荣耀',
		        	specification:'40*70',
		        	unit:'部',
		        	stockNum:'60',
		        	inventoryResults:'损',
		        	count:'100',
		        	handoverNum:'80',
		        	createDate:'2016-05-02'
		        },{
	  				goodsId:'7',
		        	stockArea:'仓储1区',
		        	stockType:'仓储区',
		        	stockLocation:'A12-2-4-008',
		        	type:'采购入库',
		        	goodsBarCode:'SP2017911',
		        	consignor:'杭州塑料制品厂',
		        	supplier:'杭州化工集团有限公司',
		        	classify:'手机',
		        	brand:'华为',
		        	batchNo:'白色',
		        	productName:'荣耀',
		        	specification:'40*70',
		        	unit:'部',
		        	stockNum:'60',
		        	inventoryResults:'损',
		        	count:'100',
		        	handoverNum:'80',
		        	createDate:'2016-05-02'
		        },{
	  				goodsId:'8',
		        	stockArea:'仓储1区',
		        	stockType:'仓储区',
		        	stockLocation:'A12-2-4-008',
		        	type:'采购入库',
		        	goodsBarCode:'SP2017912',
		        	consignor:'杭州塑料制品厂',
		        	supplier:'杭州化工集团有限公司',
		        	classify:'手机',
		        	brand:'华为',
		        	batchNo:'白色',
		        	productName:'荣耀',
		        	specification:'40*70',
		        	unit:'部',
		        	stockNum:'60',
		        	inventoryResults:'损',
		        	count:'100',
		        	handoverNum:'80',
		        	createDate:'2016-05-02'
		        },{
	  				goodsId:'9',
		        	stockArea:'仓储1区',
		        	stockType:'仓储区',
		        	stockLocation:'A12-2-4-008',
		        	type:'采购入库',
		        	goodsBarCode:'SP2017913',
		        	consignor:'杭州塑料制品厂',
		        	supplier:'杭州化工集团有限公司',
		        	classify:'手机',
		        	brand:'华为',
		        	batchNo:'白色',
		        	productName:'荣耀',
		        	specification:'40*70',
		        	unit:'部',
		        	stockNum:'60',
		        	inventoryResults:'损',
		        	count:'100',
		        	handoverNum:'80',
		        	createDate:'2016-05-02'
		        },{
	  				goodsId:'10',
		        	stockArea:'仓储1区',
		        	stockType:'仓储区',
		        	stockLocation:'A12-2-4-008',
		        	type:'采购入库',
		        	goodsBarCode:'SP2017914',
		        	consignor:'杭州塑料制品厂',
		        	supplier:'杭州化工集团有限公司',
		        	classify:'手机',
		        	brand:'华为',
		        	batchNo:'白色',
		        	productName:'荣耀',
		        	specification:'40*70',
		        	unit:'部',
		        	stockNum:'60',
		        	inventoryResults:'损',
		        	count:'100',
		        	handoverNum:'80',
		        	createDate:'2016-05-02'
		        }]
		        setTimeout(() => {
		          	this.loading = false;
		        }, 100);
	  		},
	    	onSearch:function(){
	    		this.currentPage = 1;
	        	console.log('onSearch!');
	        	this.loadData();
	    	},
	    	onClear:function(){
	    		this.formInline = {
	    			consignor:'',
	    			supplier:'',
	    			brand:'',
	    			batchNo:'',
	    			classify:'',
	    			productName:''
		        }
	    	},
	    	handleSizeChange(val) {
      			this.pageSize = val;
		      	console.log(`每页 ${val} 条`);
		      	this.loadData();
		    },
		    handleCurrentChange(val) {
		    	this.currentPage = val;
		    	this.loadData();
		      	console.log(`当前页: ${val}`);
		    }
	    }
	}
</script>